accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('job/', include('accounts.urls')),
]

jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('post-job/', views.post_job, name='post_job'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('apply/<int:job_id>/', views.apply_job, name='apply_job'),
    path('applications/<int:job_id>/', views.applications, name='applications'),
    path('update/<int:app_id>/<str:status>/', views.update_status),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit-job/<int:job_id>/', views.edit_job, name='edit_job'),
    path('delete-job/<int:job_id>/', views.delete_job, name='delete_job'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models

class EmployerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=200)

    def __str__(self):
        return self.company_name

jobs/models.py
from django.db import models
from django.contrib.auth.models import User

class Job(models.Model):
    employer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    salary = models.CharField(max_length=100,default="best industry")
    Shift=models.CharField(max_length=200,default="Day")
    exprience=models.CharField(max_length=100,default="Fresher")
    description = models.CharField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Application(models.Model):
    STATUS_CHOICES = [
        ('Applied', 'Applied'),
        ('Selected', 'Selected'),
        ('Rejected', 'Rejected')
    ]

    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    resume = models.FileField(upload_to='resumes/')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Applied')

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import EmployerProfile

def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        if User.objects.filter(username=username).exists():
            return render(request, 'register.html', {
                'error': 'User already registered'
            })

        User.objects.create_user(username=username, email=email, password=password)
        return redirect('login')

    return render(request, 'register.html')


def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is None:
            return render(request, 'login.html', {
                'error': 'Username or Password is incorrect'
            })

        login(request, user)
        return redirect('home')

    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('login')

jobs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .models import Job, Application
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Job, Application

def home(request):
    jobs = Job.objects.all().order_by('-created_at')
    title = request.GET.get('title')
    location = request.GET.get('location')

    if title:
        jobs = jobs.filter(title__icontains=title)

    if location:
        jobs = jobs.filter(location__icontains=location)

    context = {
        'jobs': jobs
    }
    return render(request, 'home.html', context)

@login_required
def post_job(request):
    if request.method == 'POST':
        Job.objects.create(
            employer=request.user,
            title=request.POST['title'],
            company=request.POST['company'],
            location=request.POST['location'],
            description=request.POST['description']
        )
        return redirect('dashboard')
    return render(request, 'job_post.html')

@login_required
def dashboard(request):
   
    jobs = Job.objects.filter(employer=request.user).order_by('-created_at')
    return render(request, 'employer_dashboard.html', {'jobs': jobs})

def apply_job(request, job_id):
    job = Job.objects.get(id=job_id)
    if request.method == 'POST':
        app = Application.objects.create(
            job=job,
            name=request.POST['name'],
            email=request.POST['email'],
            resume=request.FILES['resume']
        )

        send_mail(
            'Job Application Submitted',
            f'You have applied for {job.title}',
            'admin@jobportal.com',
            [app.email],
        )
        return redirect('home')
    return render(request, 'job_detail.html', {'job': job})

@login_required
def applications(request, job_id):
    apps = Application.objects.filter(job_id=job_id)
    return render(request, 'applications.html', {'apps': apps})

@login_required
def update_status(request, app_id, status):
    app = Application.objects.get(id=app_id)
    app.status = status
    app.save()

    if status == 'Rejected':
        send_mail(
            'Application Rejected',
            'Sorry, your application was rejected.',
            'admin@jobportal.com',
            [app.email],
        )
    if status == 'Selected':
        send_mail(
            'Application Selected',
            'Happy To Share, your application was Selected Next Level.',
            'admin@jobportal.com',
            [app.email],
        )
    return redirect('dashboard')
@login_required
def dashboard(request):
    jobs = Job.objects.filter(employer=request.user).order_by('-created_at')
    return render(request, 'employer_dashboard.html', {'jobs': jobs})

@login_required
def edit_job(request, job_id):
    job = get_object_or_404(Job, id=job_id, employer=request.user)

    if request.method == 'POST':
        job.title = request.POST['title']
        job.company = request.POST['company']
        job.location = request.POST['location']
        job.description = request.POST['description']
        job.save()
        return redirect('dashboard')

    return render(request, 'edit_job.html', {'job': job})

@login_required
def delete_job(request, job_id):
    job = get_object_or_404(Job, id=job_id, employer=request.user)
    job.delete()
    return redirect('dashboard')

templates/applications.html
{% extends 'base.html' %}
{% block content %}


<center>
    <h2>Applications</h2> <br>

<table class="app-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Resume</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead><br>

    <tbody>
        {% for app in apps %}
        <tr>
            <td>{{ app.name }}</td>
            <td>{{ app.email }}</td>
            <td>{{ app.Resume }}</td>
            <td>
                <span class="status {{ app.status|lower }}">
                    {{ app.status }}
                </span>
            </td>
            <td class="actions">
                <a href="/update/{{ app.id }}/Selected/"> <button>Select</button> </a> 
                <a href="/update/{{ app.id }}/Rejected/"> <button>Reject</button>
                </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4" class="empty">No applications found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</center>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JobFinder</title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/job_apply.css' %}">

</head>
<body>
    <script src="{% static 'js/main.js' %}"></script>
<header>
    <nav class="navbar">
        <div class="logo">
            <img src="https://images.scalebranding.com/bbc2ea6c-5408-4d3d-8265-93a53a4c2b15.png" width="50px",highet="50px">
            <h1>JobFinder</h1>
        </div>

        <ul class="nav_menu">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'home' %}">Jobs</a></li>

            {% if user.is_authenticated %}
                <li><a href="{% url 'post_job' %}">Post Job</a></li>
                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Employer Login</a></li>
                <li><a href="{% url 'register' %}">Employer Register</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

 <div class="logo-scroller">
  <div class="logos">
    <img src="https://1000logos.net/wp-content/uploads/2016/10/Apple-Logo.png" alt="Apple">
    <img src="https://1000logos.net/wp-content/uploads/2017/06/samsung-tumb.jpg" alt="Samsung">
    <img src="https://1000logos.net/wp-content/uploads/2019/06/Microsoft-Logo.jpg" alt="Microsoft">
    <img src="https://1000logos.net/wp-content/uploads/2021/11/Nike-Logo-tumb-140x88.jpg" alt="Tesla">
    <img src="https://1000logos.net/wp-content/uploads/2016/10/Amazon-Logo-tumb.png" alt="Amazon">
    <img src="https://1000logos.net/wp-content/uploads/2019/06/Google-Logo.jpg" alt="Google">
    <img src="https://1000logos.net/wp-content/themes/redwaves-lite/pic/facebook-logo-small.png" alt="Facebook">
    <img src="https://1000logos.net/wp-content/uploads/2021/09/Cognizant-Logo-tumb-1.png" alt="Adobe">
    <img src="https://1000logos.net/wp-content/uploads/2021/05/Intel-logo.png" alt="Intel">
    <img src="https://www.sealpath.com/wp-content/uploads/2022/10/wipro_primary-logo_color_rgb.png" alt="wipro">
  </div>
</div>

{% block content %}{% endblock %}

<footer class="foot">
    <p>Created by <a href="https://www.linkedin.com/in/muthuselvan-g/" target="_blank">Muthuselvan G</a></p>
</footer>

</body>
</html>

templates/edit_job.html
{% extends 'base.html' %}
{% block content %}

<div class="postjob-wrapper">
  <div class="postjob-card">
    <h2>Edit Job</h2>


    <form method="POST">
      {% csrf_token %}

      <div class="form-group">
                <label>Job Title</label>
                <input type="text" name="title" placeholder="e.g. Python Developer" value="{{ job.title }}" required>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label>Company</label>
                    <input type="text" name="company" placeholder="Company Name" value="{{ job.company }}" required>
                </div>

                <div class="form-group">
                    <label>Location</label>
                    <input type="text" name="location" placeholder="City / Remote" value="{{ job.location }}" required>
                </div>
            </div>
            <div class="form-group">
                <label>Salary Range</label>
                <input type="text" name="salary" placeholder="RS:50000" value="{{ job.salary }}" required>
            </div>
            <div class="form-group">
                <label>Shift</label>
                <input type="text" name="title" placeholder="Day or Night" value="{{ job.Shift }}" required>
            </div>
            <div class="form-group">
                <label>Exprience</label>
                <input type="text" name="title" placeholder="Fresher" value="{{ job.exprience }}" required>
            </div>

            <div class="form-group">
                <label>Job Description</label>
                <textarea name="description" rows="6" placeholder="Describe job responsibilities..." value="{{ job.description }}" required></textarea>
            </div>

      <button type="submit" class="postjob-btn" onclick="return confirm('Are you sure you want to delete this job?')">
        Update Job
      </button>
    </form>
  </div>
</div>

{% endblock %}

templates/employer_dashboard.html
{% extends 'base.html' %}
{% block content %}

<div class="dashboard">
    <h2>Employer Dashboard</h2>
<div class="dashboard-container">


    <table class="dashboard-table">
        <thead>
            <tr>
                <th>Job Title</th>
                <th>Company</th>
                <th>Location</th>
                <th>Applications</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
        {% for job in jobs %}
            <tr>
                <td>{{ job.title }}</td>
                <td>{{ job.company }}</td>
                <td>{{ job.location }}</td>

                <td>
                    <span class="badge applied">
                        {{ job.application_set.count }}
                    </span>
                </td>

                <td class="actions">
                   <span><a href="{% url 'applications' job.id %}" class="btn view">View</a></span> 
                    <span> <a href="{% url 'edit_job' job.id %}" class="btn edit">Edit</a></span> 
                    <span><a href="{% url 'delete_job' job.id %}" class="btn delete"
                       onclick="return confirm('Are you sure you want to delete this job?')">
                       Delete
                    </a></span> 
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5" class="empty">No jobs posted yet</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>


{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}

<section class="search-section">
    <h2>Find Your Dream Job</h2>
    <div class="search-bar">
    <form method="get" action="">
    <input type="text" name="title" placeholder="Job Title"
           value="{{ request.GET.title }}">

    <input type="text" name="location" placeholder="Location"
           value="{{ request.GET.location }}">

    <button type="submit">Search</button>
</form>
  </div>
</section>

<section class="job-listings-old">
    {% for job in jobs %}
    <div class="job-card-old">
        <h3>{{ job.title }}</h3>

        <p><strong>Company:</strong> {{ job.company }}</p>
        <p><strong>Location:</strong> {{ job.location }}</p>
        <p><strong>Salary:</strong> {{ job.salary }}</p>
        <p><strong>Shift:</strong> {{ job.Shift }}</p>
        <p><strong>Experience:</strong> {{ job.exprience }}</p>

        <p class="short-desc">
            <strong>Description:</strong>
            {{ job.description|truncatechars:80 }}
        </p>

        <a href="{% url 'apply_job' job.id %}">
            <button class="apply-btn">Apply</button>
        </a>
    </div>
    {% empty %}
        <p>No jobs available</p>
    {% endfor %}
</section>

</section>


{% endblock %}

templates/job_detail.html
{% extends 'base.html' %}
{% block content %}



<div class="job-apply-container">

    <div class="job-card">
        <h3>{{ job.title }}</h3>
        <p><strong>Company:</strong> {{ job.company }}</p>
        <p><strong>Location:</strong> {{ job.location }}</p>
        <p><strong>Salary:</strong>{{ job.salary }}</p>
        <p><strong>Shift:</strong>{{ job.shift }}</p>
        <p><strong>Exprience:</strong>{{ job.exprience }}</p>
        <p><strong>description:</strong>{{ job.description }}</p>
    </div>

    <div class="apply-card">
        <h3>Apply for this Job</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label>Name </label>:
            <input type="text" name="name" placeholder="Your Name" required>
            <label>Email</label>
            <input type="email" name="email" placeholder="Your Email" required>
            <label>Resume</label>
            <input type="file" name="resume"  accept="application/pdf" required>
            <button type="submit">Apply Job</button>
        </form>
    </div>

</div>

{% endblock %}

templates/job_post.html
{% extends 'base.html' %}
{% block content %}

<div class="postjob-wrapper">
    <div class="postjob-card">
        <h2>Post a New Job</h2>
        <p class="subtitle">Fill in the details to publish your job opening</p>

        <form method="POST">
            {% csrf_token %}

            <div class="form-group">
                <label>Job Title</label>
                <input type="text" name="title" placeholder="e.g. Python Developer" required>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label>Company</label>
                    <input type="text" name="company" placeholder="Company Name" required>
                </div>

                <div class="form-group">
                    <label>Location</label>
                    <input type="text" name="location" placeholder="City / Remote" required>
                </div>
            </div>
            <div class="form-group">
                <label>Salary Range</label>
                <input type="text" name="salary" placeholder="RS:15000-20000" required>
            </div>
            <div class="form-group">
                <label>Shift</label>
                <input type="text" name="title" placeholder="Day or Night" required>
            </div>
            <div class="form-group">
                <label>Exprience</label>
                <input type="text" name="title" placeholder="Fresher" required>
            </div>

            <div class="form-group">
                <label>Job Description</label>
                <textarea name="description" rows="6" placeholder="Describe job responsibilities..." required></textarea>
            </div>

            <button type="submit" class="postjob-btn">Publish Job</button>
        </form>
    </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}

<div class="login-container">
    <form method="POST" class="login-box">
        {% csrf_token %}
        <h2>Employer Login</h2>
        {% if error %}
    <div class="error-msg" id="errorMsg">{{ error }}</div>
    {% endif %}
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>

        <button type="submit">Login</button>

        <p class="link">
            Don't have an account?
            <a href="{% url 'register' %}">Register</a>
        </p>
    </form>
</div>


{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}

<div class="login-container">
    <form method="POST" class="login-box">
        {% csrf_token %}
        <h2>Employer Register</h2>
         {% if error %}
    <div class="error-msg" id="errorMsg">{{ error }}</div>
    {% endif %}
        <input type="text" name="username" placeholder="Username" required>
        <input type="text" name="company" placeholder="Company Name" required>
        <input type="password" name="password" placeholder="Password" required>

        <button type="submit",onclick=>Register</button>

        <p class="link">
            Already have an account?
            <a href="{% url 'login' %}">Login</a>
        </p>
    </form>
</div>


{% endblock %}